"""Add billing models

Revision ID: 7bcf9c57e725
Revises: 0001_initial
Create Date: 2025-09-28 23:54:17.131544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcf9c57e725'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stripe_price_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.create_unique_constraint('uq_subscription_stripe_subscription_id', ['stripe_subscription_id'])
        batch_op.create_unique_constraint('uq_subscription_stripe_customer_id', ['stripe_customer_id'])
        batch_op.create_unique_constraint('uq_subscription_tenant_id', ['tenant_id'])
        batch_op.create_foreign_key('fk_subscription_plan_id', 'plans', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscription_plan_id', type_='foreignkey')
        batch_op.drop_constraint('uq_subscription_tenant_id', type_='unique')
        batch_op.drop_constraint('uq_subscription_stripe_customer_id', type_='unique')
        batch_op.drop_constraint('uq_subscription_stripe_subscription_id', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('plan_id')

    op.drop_table('plans')
    # ### end Alembic commands ###
